/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Device } from '../../models/device';

export interface GetMyJewel_1$Params {
  ownerId: string;
  deviceId: string;
}

export function getMyJewel_1(
  http: HttpClient,
  rootUrl: string,
  params: GetMyJewel_1$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<Device>> {
  const rb = new RequestBuilder(rootUrl, getMyJewel_1.PATH, 'get');
  if (params) {
    rb.path('ownerId', params.ownerId, {});
    rb.path('deviceId', params.deviceId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Device>;
    })
  );
}

getMyJewel_1.PATH = '/api/admin/owner/{ownerId}/device/{deviceId}';
