/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Owner } from '../../models/owner';

export interface GetAllOwners$Params {}

export function getAllOwners(
  http: HttpClient,
  rootUrl: string,
  params?: GetAllOwners$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<Array<Owner>>> {
  const rb = new RequestBuilder(rootUrl, getAllOwners.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Owner>>;
    })
  );
}

getAllOwners.PATH = '/api/admin/owner';
