/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Cpu {
  cores: number;
  manufacturer: string;
  model: string;
  speed: number;
  threads: number;
}
