/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Device } from '../models/device';
export interface CreateNewJewelBody {
  jewel?: Device;
  mode: 'auto' | 'manual';
  token?: string;
}
