/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Owner {
  email: string;
  id: string;
  name: string;
  profilePicture?: string;
  roles: Array<string>;
}
