/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Bios } from './models/bios';
export type { Cpu } from './models/cpu';
export type { CreateNewJewelBody } from './models/create-new-jewel-body';
export type { Device } from './models/device';
export type { Drive } from './models/drive';
export type { Kernel } from './models/kernel';
export type { Mainboard } from './models/mainboard';
export type { OperatingSystem } from './models/operating-system';
export type { Owner } from './models/owner';
export { Type } from './models/type';
