/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createNewDeviceForOwner } from '../fn/owner/create-new-device-for-owner';
import { CreateNewDeviceForOwner$Params } from '../fn/owner/create-new-device-for-owner';
import { deleteMyJewel_1 } from '../fn/owner/delete-my-jewel-1';
import { DeleteMyJewel_1$Params } from '../fn/owner/delete-my-jewel-1';
import { Device } from '../models/device';
import { getAllOwners } from '../fn/owner/get-all-owners';
import { GetAllOwners$Params } from '../fn/owner/get-all-owners';
import { getJewelsByOwner } from '../fn/owner/get-jewels-by-owner';
import { GetJewelsByOwner$Params } from '../fn/owner/get-jewels-by-owner';
import { getMyJewel_1 } from '../fn/owner/get-my-jewel-1';
import { GetMyJewel_1$Params } from '../fn/owner/get-my-jewel-1';
import { Owner } from '../models/owner';
import { updateMyJewel_1 } from '../fn/owner/update-my-jewel-1';
import { UpdateMyJewel_1$Params } from '../fn/owner/update-my-jewel-1';

/**
 * Owner
 */
@Injectable({ providedIn: 'root' })
export class OwnerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllOwners()` */
  static readonly GetAllOwnersPath = '/api/admin/owner';

  /**
   * Gets all owners.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllOwners()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOwners$Response(
    params?: GetAllOwners$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<Array<Owner>>> {
    return getAllOwners(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets all owners.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllOwners$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOwners(params?: GetAllOwners$Params, context?: HttpContext): Observable<Array<Owner>> {
    return this.getAllOwners$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Owner>>): Array<Owner> => r.body)
    );
  }

  /** Path part for operation `getJewelsByOwner()` */
  static readonly GetJewelsByOwnerPath = '/api/admin/owner/{ownerId}/device';

  /**
   * Gets jewels by owner.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJewelsByOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJewelsByOwner$Response(
    params: GetJewelsByOwner$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<Array<Device>>> {
    return getJewelsByOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets jewels by owner.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJewelsByOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJewelsByOwner(params: GetJewelsByOwner$Params, context?: HttpContext): Observable<Array<Device>> {
    return this.getJewelsByOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Device>>): Array<Device> => r.body)
    );
  }

  /** Path part for operation `createNewDeviceForOwner()` */
  static readonly CreateNewDeviceForOwnerPath = '/api/admin/owner/{ownerId}/device';

  /**
   * Creates a new jewel for the onwer.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createNewDeviceForOwner()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewDeviceForOwner$Response(
    params: CreateNewDeviceForOwner$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<Device>> {
    return createNewDeviceForOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a new jewel for the onwer.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createNewDeviceForOwner$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewDeviceForOwner(params: CreateNewDeviceForOwner$Params, context?: HttpContext): Observable<Device> {
    return this.createNewDeviceForOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<Device>): Device => r.body)
    );
  }

  /** Path part for operation `getMyJewel_1()` */
  static readonly GetMyJewel_1Path = '/api/admin/owner/{ownerId}/device/{deviceId}';

  /**
   * Get jewel by id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyJewel_1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyJewel_1$Response(params: GetMyJewel_1$Params, context?: HttpContext): Observable<StrictHttpResponse<Device>> {
    return getMyJewel_1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get jewel by id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyJewel_1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyJewel_1(params: GetMyJewel_1$Params, context?: HttpContext): Observable<Device> {
    return this.getMyJewel_1$Response(params, context).pipe(map((r: StrictHttpResponse<Device>): Device => r.body));
  }

  /** Path part for operation `updateMyJewel_1()` */
  static readonly UpdateMyJewel_1Path = '/api/admin/owner/{ownerId}/device/{deviceId}';

  /**
   * Update the given jewel.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMyJewel_1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyJewel_1$Response(
    params: UpdateMyJewel_1$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<void>> {
    return updateMyJewel_1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update the given jewel.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMyJewel_1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyJewel_1(params: UpdateMyJewel_1$Params, context?: HttpContext): Observable<void> {
    return this.updateMyJewel_1$Response(params, context).pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }

  /** Path part for operation `deleteMyJewel_1()` */
  static readonly DeleteMyJewel_1Path = '/api/admin/owner/{ownerId}/device/{deviceId}';

  /**
   * Delete the given jewel.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteMyJewel_1()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMyJewel_1$Response(
    params: DeleteMyJewel_1$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<void>> {
    return deleteMyJewel_1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete the given jewel.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteMyJewel_1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMyJewel_1(params: DeleteMyJewel_1$Params, context?: HttpContext): Observable<void> {
    return this.deleteMyJewel_1$Response(params, context).pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }
}
